# ADOKET SYLVIA

### **DATA ANALYTICS STUDENT**

# **INTRODUCTION TO PYTHON**
## **BASIC INTRODUCTION TO SYNTAX**

**This is my first interaction with Python**

# Python data types with syntax Examples

# 1. Integer: Represent whole numbers

In [1]:
x = 20      # integer
x
print (x)

20

# 2. Float: Represents decimal number

In [2]:
y = 3.15
y

3.15

## 3. String: Represents a sequence of characters

In [3]:
name = "Adoket Sylvia"
name

'Adoket Sylvia'

In [4]:
greeting =" HELL0"
greeting

' HELL0'

# 4. Boolem: Represents

In [5]:
is_valid = True    # Boolem
is_valid

True

In [6]:
is_active = False  # Boolem
is_active

False

# 5. LIST: An ordered, mutable collection of items

In [7]:
fruits = ( "apple", " banana" , "orange" )
fruits

('apple', ' banana', 'orange')

In [8]:
fruits = ( "apple" , "banana" , "orange" )
print(fruits [0])

apple

# 6.Tuple:

In [9]:
my_tuple =( 1,2,3 )
my_tuple

(1, 2, 3)

# 7.Set:

In [10]:
my_set = { 1,2,3, "John" }
my_set

{1, 2, 3, 'John'}

# 8. Dictionary: A collection of key-value pairs

In [11]:
my_dict = { 
    "Name" :  "Sylvia" ,
    "Age"  : 24,
    "Occupation" : "Data Analysts" }
my_dict

{'Name': 'Sylvia', 'Age': 24, 'Occupation': 'Data Analysts'}

In [12]:
print(my_dict['Name'])

Sylvia

#  9. Conditional statement

 # 1. if Statement ( do something if true )

In [13]:
age = 18

if age >= 18:
    print("You are an adult")

You are an adult

In [14]:
age = 10

if age >= 18:
    print("You are an adult")
else:
    print("You are a minor")

You are a minor

In [15]:
score = 85

if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
elif score >= 70:
    print("Grade: C")
else:
    print("Grade: F")

Grade: B

In [16]:
score = 70

if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
elif score >= 70:
    print("Grade: C")
else:
    print("Grade: F")

Grade: C

In [17]:
score = 40

if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
elif score >= 70:
    print("Grade: C")
else:
    print("Grade: F")

Grade: F

In [18]:
score = 91

if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
elif score >= 70:
    print("Grade: C")
else:
    print("Grade: F")

Grade: A

In [19]:
score = 41

if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
elif score >= 70:
    print("Grade: C")
else:
    print("Grade: F")

Grade: F

# Basics for loop

# What is a loop

In [20]:
# for a loop
for i in range(5):
    print(i)

0
1
2
3
4

In [21]:
# for a loop
for i in range(3):
    print(i)

0
1
2

In [22]:
# for a loop
for i in range(8):
    print(i)

0
1
2
3
4
5
6
7

# Loop through a list

In [23]:
fruits = ['apple', 'banana', 'cherry']
for fruit in fruits:
    print(fruit)

apple
banana
cherry

# Loop through a string

In [24]:
word = "Python"

for letter in word:
    print(letter)

P
y
t
h
o
n

# DS Examples-Loop through DataFrame

In [25]:
import pandas as pd

# Create sample data
data ={
    'name': ['Alice', 'Bob', 'Charlie'],
    'score': [85, 62, 90] 
}

df = pd.DataFrame(data)
df

      name  score
0    Alice     85
1      Bob     62
2  Charlie     90

In [26]:
import pandas as pd

# Create sample data
data ={
    'name': ['Alice', 'Bob', 'Charlie'],
    'score': [85, 62, 90] 
}

df = pd.DataFrame(data)

#Loop through rows
for index, row in df.iterrows():
    print(f"{row['name']} scored {row['score']}")

Alice scored 85
Bob scored 62
Charlie scored 90

# 12. Functions

In [27]:
def greet(name):
    return "Hello, " + name

print(greet("Alice"))

Hello, Alice

# 13.Install Necessary libraries

In [28]:
#!pip install pandas
#!pip install numpy
#!pip install seaborn
#!pip install matplotlib
#!pip install wordcloud
#!pip install pillow
#!pip install plotly.express

# 14. Importing Libraries

In [29]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Mathemetical Operations

# 1. Basic Arithmetic Operations

In [30]:
x = 10
y = 3

addition = x + y  # Addition
subtraction = x - y  #Subtraction
multiplication = x * y #Multiplication
division = x / y       # Division (returns float)
floor_division = x // y #Floor division (integer division)
modulus = x % y        # Modulus (remainder)
exponentiation = x ** y # Exponentiation

# 2. Using Built-in Math Functions

In [31]:
import math

square_root = math.sqrt(25)  # Square root
absolute_value = abs(8)      #Absolute value
power = pow(3, 3)            # 3 raised to the power of 3
logarithm = math.log10(100)  # Natural Logarithm (ln)
log_base_10 = math.log10(100) # Logarithm base 10
factorial = math.factorial(5)  # Factorial of 5

print(square_root, absolute_value, power, logarithm, log_base_10, factorial)

5.0 8 27 2.0 2.0 120

# 3. **Rounding off**

In [32]:
import math
num = 5.6789
rounded_value = round(num, 3) # Round to 2 decimal places
floor_value = math.floor(num) # Floor (round down)
ceil_value = math.ceil(num)
print(rounded_value, floor_value, ceil_value)

5.679 5 6

# **Working with Vectors in Python**

In [33]:
import numpy as np

# creating a vector
vector_a = np.array([1, 2, 3])
vector_a

array([1, 2, 3])

In [34]:
vector_b = np.array([4, 5, 6])
vector_b

array([4, 5, 6])

# **Vector Addition**

In [35]:
vector_sum = vector_a + vector_b
vector_sum

array([5, 7, 9])

# **Vector Subtraction**

In [36]:
vector_diff = vector_a - vector_b
vector_diff

array([-3, -3, -3])

# **Scalar Multiplication**

In [37]:
scalar_multiplication = 3 *vector_a
scalar_multiplication

array([3, 6, 9])

## Dot Product

In [38]:
dot_product = np.dot(vector_a, vector_b)
dot_product

np.int64(32)

## Magnitude of a Vector

In [39]:
magnitude_a = np.linalg.norm(vector_a)
magnitude_a
rounded_magnitude_value = round(magnitude_a, 3)
print(rounded_magnitude_value)

3.742

In [40]:
print("Vector A:", vector_a)
print("Vector B:", vector_b)

Vector A: [1 2 3]
Vector B: [4 5 6]

## Working with Lists in Python

## Creating a list

In [41]:
fruits = ["Apple", "Banana", "Cherry", "Date"]
fruits

['Apple', 'Banana', 'Cherry', 'Date']

## Accessing elements

In [42]:
first_fruit = fruits[0]  # Access first element
first_fruit

'Apple'

In [43]:
last_fruit =fruits[-1]  # Access last element
last_fruit

'Date'

## Modifying elements

In [44]:
fruits[1] = "Blueberry" # Change Banana to Blueberry
fruits

['Apple', 'Blueberry', 'Cherry', 'Date']

In [45]:
fruits.append("Elderberry")  # Append new element to the end
fruits.insert(2, "Coconut")  # Insert at index 2

In [46]:
deleted_fruit = fruits.pop(3)  # Remove and return element at index 3
fruits.remove("Date")   # Remove first occurrence of "Apple"
fruits

['Apple', 'Blueberry', 'Coconut', 'Elderberry']

# List slicing

In [47]:
subset_fruits = fruits[1:3]  # Get elements from index 1 to 2
subset_fruits

['Blueberry', 'Coconut']

## Iterating over a list

In [48]:
for fruit in fruits:
    print(fruit)

Apple
Blueberry
Coconut
Elderberry

# Sorting a list

In [49]:
fruits.sort()  # Sort alphabetically
fruits

['Apple', 'Blueberry', 'Coconut', 'Elderberry']

# Finding the length of a list

In [50]:
num_fruits = len(fruits)
num_fruits

4

In [51]:
print("Updated Fruits List:", fruits)
print("Deletef Fruit:", deleted_fruit)
print("Subset of Fruits:", subset_fruits)
print("Number of Fruits:", num_fruits)

Updated Fruits List: ['Apple', 'Blueberry', 'Coconut', 'Elderberry']
Deletef Fruit: Cherry
Subset of Fruits: ['Blueberry', 'Coconut']
Number of Fruits: 4

## **MATRICES**

## What is a Matrix?

In [52]:
import numpy as np

# Create two 2x2 matrices
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[2, 0],
              [1, 2]])

In [53]:
# Perform operations
print("A + B =\n", A + B)

A + B =
 [[3 2]
 [4 6]]

In [54]:
print("\nA - B =\n", A - B)

A - B =
 [[-1  2]
 [ 2  2]]

# Create DataFrame Using Pandas ( Most common)

In [55]:
import pandas as pd

# Creating a DataFrame
data = {"Name": ["Alice", "Bob", "Charlie", "David", "Dan"],
        "Age": [25, 30, 40, 80,22],
        "County": ["Embu", "Nyeri", "Busia", "Bomet", "Meru"]
       }

df = pd.DataFrame(data)
df

      Name  Age County
0    Alice   25   Embu
1      Bob   30  Nyeri
2  Charlie   40  Busia
3    David   80  Bomet
4      Dan   22   Meru

In [56]:
df["County"]

0     Embu
1    Nyeri
2    Busia
3    Bomet
4     Meru
Name: County, dtype: object

In [57]:
df["Name"]

0      Alice
1        Bob
2    Charlie
3      David
4        Dan
Name: Name, dtype: object

In [58]:
df["Age"]

0    25
1    30
2    40
3    80
4    22
Name: Age, dtype: int64

In [59]:
print("\nAccessing first row:")
print(df.iloc[0])

Accessing first row:
Name      Alice
Age          25
County     Embu
Name: 0, dtype: object

In [60]:
print("\nAccessing second row:")
print(df.iloc[1])

Accessing second row:
Name        Bob
Age          30
County    Nyeri
Name: 1, dtype: object

In [61]:
df["Salary"] = [50000, 60000, 70000, 80000, 90000]
df['occupation'] = ['Nurse', 'Teacher', 'Politician', 'Doctor', 'Nurse']
df

      Name  Age County  Salary  occupation
0    Alice   25   Embu   50000       Nurse
1      Bob   30  Nyeri   60000     Teacher
2  Charlie   40  Busia   70000  Politician
3    David   80  Bomet   80000      Doctor
4      Dan   22   Meru   90000       Nurse

In [62]:
df[df["Age"] > 40]

    Name  Age County  Salary occupation
3  David   80  Bomet   80000     Doctor

In [63]:
df.sort_values(by="Age", ascending=False)

      Name  Age County  Salary  occupation
3    David   80  Bomet   80000      Doctor
2  Charlie   40  Busia   70000  Politician
1      Bob   30  Nyeri   60000     Teacher
0    Alice   25   Embu   50000       Nurse
4      Dan   22   Meru   90000       Nurse

In [66]:
df.sort_values(by="Age", ascending=True)

      Name  Age County  Salary  occupation
4      Dan   22   Meru   90000       Nurse
0    Alice   25   Embu   50000       Nurse
1      Bob   30  Nyeri   60000     Teacher
2  Charlie   40  Busia   70000  Politician
3    David   80  Bomet   80000      Doctor

In [65]:
df.groupby("County")["Age"].mean()

County
Bomet    80.0
Busia    40.0
Embu     25.0
Meru     22.0
Nyeri    30.0
Name: Age, dtype: float64

## **Handling Missing Data**
### Introducing a missing value

In [74]:
df.loc[2, "Salary"] = None
df

      Name  Age County   Salary  occupation
0    Alice   25   Embu  50000.0       Nurse
1      Bob   30  Nyeri  60000.0     Teacher
2  Charlie   40  Busia      NaN  Politician
3    David   80  Bomet  80000.0      Doctor
4      Dan   22   Meru  90000.0       Nurse

# Suppress Warnings

In [78]:
import warnings

warnings.simplefilter("ignore")

In [79]:
print("\nFilling missing values with mean salary:")
df["Salary"].fillna(df["Salary"].mean(), inplace=True)
df

Filling missing values with mean salary:

      Name  Age County   Salary  occupation
0    Alice   25   Embu  50000.0       Nurse
1      Bob   30  Nyeri  60000.0     Teacher
2  Charlie   40  Busia  70000.0  Politician
3    David   80  Bomet  80000.0      Doctor
4      Dan   22   Meru  90000.0       Nurse

# Introduce a missing value (Categorical)

In [80]:
df.loc[2, "occupation"] = None
df

      Name  Age County   Salary occupation
0    Alice   25   Embu  50000.0      Nurse
1      Bob   30  Nyeri  60000.0    Teacher
2  Charlie   40  Busia  70000.0       None
3    David   80  Bomet  80000.0     Doctor
4      Dan   22   Meru  90000.0      Nurse

## Replace the missing value (Categorical)

In [82]:
df["occupation"].fillna(df["occupation"].mode()[0], inplace=True)
df

      Name  Age County   Salary occupation
0    Alice   25   Embu  50000.0      Nurse
1      Bob   30  Nyeri  60000.0    Teacher
2  Charlie   40  Busia  70000.0      Nurse
3    David   80  Bomet  80000.0     Doctor
4      Dan   22   Meru  90000.0      Nurse

# Exercise: Create a dataframe as guided below

In [84]:
data = {
    'Name': ['Peter', 'Mercy', 'Sylvia', 'Kevo','Brian', 'Paul', 'Nancy', 'Milio', 'Maxy', 'Ivy'],
    'Age': [22, 27, 26, 23, 21, 20, 30, 32, 34, 35],
    'Salary': [50000, 60000, 40000, 50000, 60000, 70000, 40000, 30000, 75000, 90000],
    'County': ['Tharaka Nithi', 'Meru', 'Embu', 'Nanyuki', 'Kirinyaga', 'Muranga', 'Kisumu', 'Eldoret', 'Nakuru', 'Kitale'],
    'Institutions': ['Chuka University', 'Embu University', 'Meru University', 'Tharaka University', 'Isiolo University', 'Maasai Mara University', 'Nairobi University', 'Muranga University', 'Kirinyaga University', 'Kabarak University']
}
df = pd.DataFrame(data)
print(df)

     Name  Age  Salary         County            Institutions
0   Peter   22   50000  Tharaka Nithi        Chuka University
1   Mercy   27   60000           Meru         Embu University
2  Sylvia   26   40000           Embu         Meru University
3    Kevo   23   50000        Nanyuki      Tharaka University
4   Brian   21   60000      Kirinyaga       Isiolo University
5    Paul   20   70000        Muranga  Maasai Mara University
6   Nancy   30   40000         Kisumu      Nairobi University
7   Milio   32   30000        Eldoret      Muranga University
8    Maxy   34   75000         Nakuru    Kirinyaga University
9     Ivy   35   90000         Kitale      Kabarak University

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          10 non-null     object
 1   Age           10 non-null     int64
 2   Salary        10 non-null     int64
 3   County        10 non-null     object
 4   Institutions  10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes